### ISSUE TITLE
Would like access to query and params

### ISSUE THREAD

**Issue by Sigfried** [KenPowers/connect-static-transform#6]
The static transform I want to do depends on query string or url parameters. I can't figure out how to access these in combination with connect-static-transform. I'm new to Node, so maybe I'm missing something.

**Comment by KenPowers** [comment]
That currently isn't possible with this library alone due to this line: https://github.com/KenPowers/connect-static-transform/blob/b8bcf8b0aa4be49bc4c28e2a7a2bdf021148aa45/lib/staticTransform.js#L58

I'll accept a pull request if you want to roll up a solution. Something like additionally passing along the parsed url object instead of just the `pathname`.

Might also be able to do something with `path` instead of `pathname`, but before wandering down that path this library really needs some unit tests. https://nodejs.org/api/url.html
